version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.2.0

jobs:
  deploy-ui:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install AWS CLI 
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            chmod +x deploy-ui.sh  # Ensure deploy-ui.sh is executable
            ./deploy-ui.sh
  
  # using npx as aws-cdk is installed locally
  deploy-infra:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Deploying Infrastructure
          command: |
            cd cdk
            npm install aws-cdk
            npm install
            npx cdk deploy --require-approval-never 



workflows:
  build_and_deploy:
    jobs:
      - APPROVE-DEPLOY-INFRA ?:
          type: approval
          filters:
            branches:
              only:
                - main
      - deploy-infra:
          context:
            - aws-context
          requires:
            - APPROVE-DEPLOY-INFRA ?
      - APPROVE-DEPLOY-UI ?:
          type: approval
          filters:
            branches:
              only:
                - main
      - deploy-ui:
          context:
            - aws-context
          requires:
            - APPROVE-DEPLOY-UI ?
