version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  deploy-ui:
    executor: node-executor
    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      # Execute deploy.sh script
      - run:
          name: Deploy to S3
          command: |
            chmod +x deploy-ui.sh  # Ensure deploy-ui.sh is executable
            ./deploy-ui.sh
    deploy-infra:
    executor: node-executor
    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      # Execute deploy.sh script
      - run:
          name: Deploy Infra
          command: |
            cd cdk
            npm install
            npm run build
            cdk deploy CdkStack --require-approval never

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - DEPLOY INFRASTRUCTURE ?:
          type: approval
      - deploy-infra:
          context:
            - aws-context
          requires:
            - DEPLOY INFRASTRUCTURE ?
      - DEPLOY UI ?:
          type: approval
      - deploy-ui:
          context:
            - aws-context
          requires:
            - DEPLOY UI ?
          filters:
            branches:
              only:
                - main  # Replace with your main branch name
