version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.2.0
  cdk-executor:
    docker:
      - image: circleci/node:14.17

jobs:
  deploy-ui:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install AWS CLI 
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            chmod +x deploy-ui.sh  # Ensure deploy-ui.sh is executable
            ./deploy-ui.sh
  
  deploy-infra:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: commands execution
          command: |
            cd cdk
            npm install aws-cdk
            npm install
            npx cdk deploy --require-approval-never



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-infra:
          context:
            - aws-context
          filters:
            branches:
              only:
                - main  
